version: '3'

services:
  suricata_analyzer:
    build: .
    volumes:
      - /var/log/suricata:/var/log/suricata:ro
      - ./output:/output
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - EVE_JSON_LOG_PATH=/var/log/suricata/eve.json
      - OUTPUT_DIR=/output
